### ISSUE TITLE
-let?

### ISSUE THREAD

**Issue by alphapapa** [facetframer/orgnav#2]
Hey, it's me again, looking through your code.  I'm very impressed, this is very well organized and documented.  Hope you'll put it on MELPA soon!

Just a quick suggestion, looking at https://github.com/facetframer/orgnav/blob/master/orgnav.el#L201, have you thought about using `-let`?  It has plist support, which would reduce a lot of the boilerplate here.

**Comment by facetframer** [comment]
Nice. I didn't know `-let` existed. I had given up on `pcase` and `destructuring-bind` as too unwieldy to use.

This seems like a good suggestion. 

I've created an issue #3 for releasing this on MELPA.

**Comment by facetframer** [comment]
Mostly done:  https://github.com/facetframer/orgnav/commit/ebb71097c72bc1a08f5cffc1a6a62d27fbdf487b

I should still do a search and replace over the project

**Comment by talwrii** [comment]
```
> git show-ref --head | head -n 1
7968777077eeca568b0dea3f8cd61252e35e5cf5 HEAD
> grep 'plist-get' -ir *.el
orgnav.el:       (setq result (plist-put result key (plist-get update-plist key))))
orgnav-refile.el:    (setq options (orgnav--plist-update options :depth (or (plist-get options :depth) orgnav-refile-depth)))
orgnav-refile.el:  (setq options (orgnav--plist-update options :depth (or (plist-get options :depth) orgnav-refile-depth)))
```

**Comment by facetframer** [comment]
Okay that's most of the `plist-get`s killed off as of https://github.com/facetframer/orgnav/commit/7968777077eeca568b0dea3f8cd61252e35e5cf5

```
> git show-ref --head | head -n 1
7968777077eeca568b0dea3f8cd61252e35e5cf5 HEAD
> grep 'plist-get' -ir *.el
orgnav.el:       (setq result (plist-put result key (plist-get update-plist key))))
orgnav-refile.el:    (setq options (orgnav--plist-update options :depth (or (plist-get options :depth) orgnav-refile-depth)))
orgnav-refile.el:  (setq options (orgnav--plist-update options :depth (or (plist-get options :depth) orgnav-refile-depth)))
```
